# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "Home"
  url = "#about"
  weight = 2.5

[[main]]
  name = "What I can do"
  url = "#file:///C:/Users/Richard%20Boat/Desktop/Application%20phd/Job%20resume/What_I_can_do.html"
  weight = 20

#[[main]]
  #name = "Projects"
  #url = "#projects"
  #weight = 30

#[[main]]
  #name = "Publications"
  #url = "#featured"
  #weight = 40

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 3.5

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
 [[main]]
    name = "CV"
    url = "https://www.dropbox.com/s/pmn6lx864i5np9d/Richard%20Adjei-Boateng_CV.pdf?dl=0"
    weight = 4.5
